<a href="https://colab.research.google.com/github/Yukthakarkera/AI-and-ML/blob/main/Principle_Component__Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [16]:
data=pd.read_csv("/content/exe1data.txt")
print(data)

     6.1101    17.592
0    5.5277   9.13020
1    8.5186  13.66200
2    7.0032  11.85400
3    5.8598   6.82330
4    8.3829  11.88600
..      ...       ...
91   5.8707   7.20290
92   5.3054   1.98690
93   8.2934   0.14454
94  13.3940   9.05510
95   5.4369   0.61705

[96 rows x 2 columns]


In [17]:
#compute mean of the data
mean_value=np.mean(data,axis=0)
print("Mean Value")
print(mean_value)

Mean Value
6.1101    8.181151
17.592    5.716709
dtype: float64


In [19]:
#To obtain standardize value  Subtract mean from the given data.
std_value=(data-mean_value)
print("Standardized values are")
print(std_value)

Standardized values are
      6.1101    17.592
0  -2.653451  3.413491
1   0.337449  7.945291
2  -1.177951  6.137291
3  -2.321351  1.106591
4   0.201749  6.169291
..       ...       ...
91 -2.310451  1.486191
92 -2.875751 -3.729809
93  0.112249 -5.572169
94  5.212849  3.338391
95 -2.744251 -5.099659

[96 rows x 2 columns]


In [20]:
#Calculate the covariance matrix.
cov_matrix=np.cov(std_value, rowvar=False)
print(cov_matrix)
print("Shape of covariance matrix :",cov_matrix.shape)
print("size of covariance matrix :",cov_matrix.size)

[[15.089  18.3112]
 [18.3112 29.2135]]
Shape of covariance matrix : (2, 2)
size of covariance matrix : 4


In [21]:
#Calculate the eigen vectors and eigen values of the covariance matrix.
eigenvalues,eigenvector=np.linalg.eigh(cov_matrix)
print("eigenvalues")
print(eigenvalues)
print("\neigenvector")
print(eigenvector)

eigenvalues
[ 2.5254 41.7771]

eigenvector
[[-0.8246  0.5658]
 [ 0.5658  0.8246]]


In [22]:
#sort eigen values and corresponding eigen vectors in descending order
sorted_value=np.argsort(eigenvalues)[::-1]
eigenvalues=eigenvalues[sorted_value]
eigenvector=eigenvector[:,sorted_value]
print(eigenvalues)
print(eigenvector)

[41.7771  2.5254]
[[ 0.5658 -0.8246]
 [ 0.8246  0.5658]]


In [23]:
#choose the number of principle componenets
n_components=1
selected_eigenvector=eigenvector[:,:n_components]
result=np.dot(std_value,selected_eigenvector)
print("final result")
print(result)

final result
[[ 1.3135]
 [ 6.7424]
 [ 4.3942]
 [-0.4008]
 [ 5.2012]
 [-1.5271]
 [ 5.4056]
 [-0.2317]
 [-3.3356]
 [-3.4298]
 [11.456 ]
 [-3.4967]
 [ 1.3729]
 [-5.5606]
 [-3.4023]
 [-1.3669]
 [-5.9776]
 [-2.6936]
 [-0.8982]
 [-3.2529]
 [20.074 ]
 [-2.7212]
 [-1.4859]
 [-3.6523]
 [20.0425]
 [ 9.0477]
 [ 2.6671]
 [10.2266]
 [23.1301]
 [-7.3768]
 [-0.6697]
 [ 5.8952]
 [-4.484 ]
 [ 0.698 ]
 [-1.0921]
 [-1.3678]
 [-3.373 ]
 [ 6.2619]
 [-1.2149]
 [-5.8245]
 [-2.2232]
 [ 1.7221]
 [-4.0634]
 [ 0.6354]
 [-4.4667]
 [-2.2408]
 [-4.5397]
 [ 3.8771]
 [-5.3679]
 [ 0.4897]
 [-4.8226]
 [-1.6061]
 [-0.9196]
 [-4.5859]
 [-6.9166]
 [-3.7514]
 [-2.3552]
 [-0.8078]
 [ 0.4704]
 [-0.0868]
 [-7.0246]
 [17.4801]
 [ 9.0313]
 [15.446 ]
 [-1.2304]
 [ 0.0871]
 [ 2.8601]
 [-5.3922]
 [19.4751]
 [ 1.9002]
 [-1.8732]
 [-4.8902]
 [-2.4993]
 [-8.7088]
 [-5.3932]
 [-1.8743]
 [-1.7917]
 [ 2.0382]
 [-4.756 ]
 [-5.7056]
 [-6.2386]
 [-5.187 ]
 [ 2.4045]
 [-1.2498]
 [-1.0263]
 [ 1.4569]
 [-5.1824]
 [-6.0938]
 [-4.1535]
 [-4.591